name:                timer
version:             0.2.0.0
github:              "paasim/timer"
license:             BSD3
author:              "Markus Paasiniemi"
maintainer:          "paasim@iki.fi"
copyright:           "2018 Markus Paasiniemi"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/paasim/timer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  timer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timer

tests:
  timer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timer
